include $(TEST_ROOT)/common/test_rpx.mk

ifeq ($(shell uname -o),Cygwin)
COMMON_DIR := $(shell cygpath -w ${TEST_ROOT})/common
else
COMMON_DIR := $(TEST_ROOT)/common
endif

INCLUDES := -I$(COMMON_DIR)

.PHONY: all clean
