#pragma once
#include "common/types.h"

namespace latte
{

union TD_PS_SAMPLER_BORDERN_RED
{
   uint32_t value;
   float BORDER_RED;
};

union TD_PS_SAMPLER_BORDERN_GREEN
{
   uint32_t value;
   float BORDER_GREEN;
};

union TD_PS_SAMPLER_BORDERN_BLUE
{
   uint32_t value;
   float BORDER_BLUE;
};

union TD_PS_SAMPLER_BORDERN_ALPHA
{
   uint32_t value;
   float BORDER_ALPHA;
};

using TD_VS_SAMPLER_BORDERN_RED     = TD_PS_SAMPLER_BORDERN_RED;
using TD_VS_SAMPLER_BORDERN_GREEN   = TD_PS_SAMPLER_BORDERN_GREEN;
using TD_VS_SAMPLER_BORDERN_BLUE    = TD_PS_SAMPLER_BORDERN_BLUE;
using TD_VS_SAMPLER_BORDERN_ALPHA   = TD_PS_SAMPLER_BORDERN_ALPHA;

using TD_GS_SAMPLER_BORDERN_RED     = TD_PS_SAMPLER_BORDERN_RED;
using TD_GS_SAMPLER_BORDERN_GREEN   = TD_PS_SAMPLER_BORDERN_GREEN;
using TD_GS_SAMPLER_BORDERN_BLUE    = TD_PS_SAMPLER_BORDERN_BLUE;
using TD_GS_SAMPLER_BORDERN_ALPHA   = TD_PS_SAMPLER_BORDERN_ALPHA;

} // namespace latte
