/*

    GLX loader generated by glad 0.1.33 on Mon Sep 30 18:19:57 2019.

    Language/Generator: C/C++ Debug
    Specification: glx
    APIs: glx=1.4
    Profile: -
    Extensions:
        GLX_ARB_create_context,
        GLX_ARB_create_context_profile,
        GLX_EXT_swap_control,
        GLX_SGIX_pbuffer
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --api="glx=1.4" --generator="c-debug" --spec="glx" --extensions="GLX_ARB_create_context,GLX_ARB_create_context_profile,GLX_EXT_swap_control,GLX_SGIX_pbuffer"
    Online:
        https://glad.dav1d.de/#language=c-debug&specification=glx&loader=on&api=glx%3D1.4&extensions=GLX_ARB_create_context&extensions=GLX_ARB_create_context_profile&extensions=GLX_EXT_swap_control&extensions=GLX_SGIX_pbuffer
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glad/glad_glx.h>

extern GLADcallback _pre_call_callback;
extern GLADcallback _post_call_callback;

static void* get_proc(const char *namez);

#if defined(_WIN32) || defined(__CYGWIN__)
#ifndef _WINDOWS_
#undef APIENTRY
#endif
#include <windows.h>
static HMODULE libGL;

typedef void* (APIENTRYP PFNWGLGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNWGLGETPROCADDRESSPROC_PRIVATE gladGetProcAddressPtr;

#ifdef _MSC_VER
#ifdef __has_include
  #if __has_include(<winapifamily.h>)
    #define HAVE_WINAPIFAMILY 1
  #endif
#elif _MSC_VER >= 1700 && !_USING_V110_SDK71_
  #define HAVE_WINAPIFAMILY 1
#endif
#endif

#ifdef HAVE_WINAPIFAMILY
  #include <winapifamily.h>
  #if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
    #define IS_UWP 1
  #endif
#endif

static
int open_gl(void) {
#ifndef IS_UWP
    libGL = LoadLibraryW(L"opengl32.dll");
    if(libGL != NULL) {
        void (* tmp)(void);
        tmp = (void(*)(void)) GetProcAddress(libGL, "wglGetProcAddress");
        gladGetProcAddressPtr = (PFNWGLGETPROCADDRESSPROC_PRIVATE) tmp;
        return gladGetProcAddressPtr != NULL;
    }
#endif

    return 0;
}

static
void close_gl(void) {
    if(libGL != NULL) {
        FreeLibrary((HMODULE) libGL);
        libGL = NULL;
    }
}
#else
#include <dlfcn.h>
static void* libGL;

#if !defined(__APPLE__) && !defined(__HAIKU__)
typedef void* (APIENTRYP PFNGLXGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNGLXGETPROCADDRESSPROC_PRIVATE gladGetProcAddressPtr;
#endif

static
int open_gl(void) {
#ifdef __APPLE__
    static const char *NAMES[] = {
        "../Frameworks/OpenGL.framework/OpenGL",
        "/Library/Frameworks/OpenGL.framework/OpenGL",
        "/System/Library/Frameworks/OpenGL.framework/OpenGL",
        "/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL"
    };
#else
    static const char *NAMES[] = {"libGL.so.1", "libGL.so"};
#endif

    unsigned int index = 0;
    for(index = 0; index < (sizeof(NAMES) / sizeof(NAMES[0])); index++) {
        libGL = dlopen(NAMES[index], RTLD_NOW | RTLD_GLOBAL);

        if(libGL != NULL) {
#if defined(__APPLE__) || defined(__HAIKU__)
            return 1;
#else
            gladGetProcAddressPtr = (PFNGLXGETPROCADDRESSPROC_PRIVATE)dlsym(libGL,
                "glXGetProcAddressARB");
            return gladGetProcAddressPtr != NULL;
#endif
        }
    }

    return 0;
}

static
void close_gl(void) {
    if(libGL != NULL) {
        dlclose(libGL);
        libGL = NULL;
    }
}
#endif

static
void* get_proc(const char *namez) {
    void* result = NULL;
    if(libGL == NULL) return NULL;

#if !defined(__APPLE__) && !defined(__HAIKU__)
    if(gladGetProcAddressPtr != NULL) {
        result = gladGetProcAddressPtr(namez);
    }
#endif
    if(result == NULL) {
#if defined(_WIN32) || defined(__CYGWIN__)
        result = (void*)GetProcAddress((HMODULE) libGL, namez);
#else
        result = dlsym(libGL, namez);
#endif
    }

    return result;
}

int gladLoadGLX(Display *dpy, int screen) {
    int status = 0;

    if(open_gl()) {
        status = gladLoadGLXLoader((GLADloadproc)get_proc, dpy, screen);
        close_gl();
    }

    return status;
}

static Display *GLADGLXDisplay = 0;
static int GLADGLXscreen = 0;

static int get_exts(void) {
    return 1;
}

static void free_exts(void) {
    return;
}

static int has_ext(const char *ext) {
    const char *terminator;
    const char *loc;
    const char *extensions;

    if(!GLAD_GLX_VERSION_1_1)
        return 0;

    extensions = glXQueryExtensionsString(GLADGLXDisplay, GLADGLXscreen);

    if(extensions == NULL || ext == NULL)
        return 0;

    while(1) {
        loc = strstr(extensions, ext);
        if(loc == NULL)
            break;

        terminator = loc + strlen(ext);
        if((loc == extensions || *(loc - 1) == ' ') &&
            (*terminator == ' ' || *terminator == '\0'))
        {
            return 1;
        }
        extensions = terminator;
    }

    return 0;
}

int GLAD_GLX_VERSION_1_0 = 0;
int GLAD_GLX_VERSION_1_1 = 0;
int GLAD_GLX_VERSION_1_2 = 0;
int GLAD_GLX_VERSION_1_3 = 0;
int GLAD_GLX_VERSION_1_4 = 0;
PFNGLXCHOOSEFBCONFIGPROC glad_glXChooseFBConfig;
GLXFBConfig * APIENTRY glad_debug_impl_glXChooseFBConfig(Display * arg0, int arg1, const int * arg2, int * arg3) {    
    GLXFBConfig * ret;
    _pre_call_callback("glXChooseFBConfig", (void*)glXChooseFBConfig, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXChooseFBConfig(arg0, arg1, arg2, arg3);
    _post_call_callback("glXChooseFBConfig", (void*)glXChooseFBConfig, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXCHOOSEFBCONFIGPROC glad_debug_glXChooseFBConfig = glad_debug_impl_glXChooseFBConfig;
PFNGLXCHOOSEVISUALPROC glad_glXChooseVisual;
XVisualInfo * APIENTRY glad_debug_impl_glXChooseVisual(Display * arg0, int arg1, int * arg2) {    
    XVisualInfo * ret;
    _pre_call_callback("glXChooseVisual", (void*)glXChooseVisual, 3, arg0, arg1, arg2);
    ret =  glad_glXChooseVisual(arg0, arg1, arg2);
    _post_call_callback("glXChooseVisual", (void*)glXChooseVisual, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXCHOOSEVISUALPROC glad_debug_glXChooseVisual = glad_debug_impl_glXChooseVisual;
PFNGLXCOPYCONTEXTPROC glad_glXCopyContext;
void APIENTRY glad_debug_impl_glXCopyContext(Display * arg0, GLXContext arg1, GLXContext arg2, unsigned long arg3) {    
    _pre_call_callback("glXCopyContext", (void*)glXCopyContext, 4, arg0, arg1, arg2, arg3);
     glad_glXCopyContext(arg0, arg1, arg2, arg3);
    _post_call_callback("glXCopyContext", (void*)glXCopyContext, 4, arg0, arg1, arg2, arg3);
    
}
PFNGLXCOPYCONTEXTPROC glad_debug_glXCopyContext = glad_debug_impl_glXCopyContext;
PFNGLXCREATECONTEXTPROC glad_glXCreateContext;
GLXContext APIENTRY glad_debug_impl_glXCreateContext(Display * arg0, XVisualInfo * arg1, GLXContext arg2, Bool arg3) {    
    GLXContext ret;
    _pre_call_callback("glXCreateContext", (void*)glXCreateContext, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXCreateContext(arg0, arg1, arg2, arg3);
    _post_call_callback("glXCreateContext", (void*)glXCreateContext, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXCREATECONTEXTPROC glad_debug_glXCreateContext = glad_debug_impl_glXCreateContext;
PFNGLXCREATEGLXPIXMAPPROC glad_glXCreateGLXPixmap;
GLXPixmap APIENTRY glad_debug_impl_glXCreateGLXPixmap(Display * arg0, XVisualInfo * arg1, Pixmap arg2) {    
    GLXPixmap ret;
    _pre_call_callback("glXCreateGLXPixmap", (void*)glXCreateGLXPixmap, 3, arg0, arg1, arg2);
    ret =  glad_glXCreateGLXPixmap(arg0, arg1, arg2);
    _post_call_callback("glXCreateGLXPixmap", (void*)glXCreateGLXPixmap, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXCREATEGLXPIXMAPPROC glad_debug_glXCreateGLXPixmap = glad_debug_impl_glXCreateGLXPixmap;
PFNGLXCREATENEWCONTEXTPROC glad_glXCreateNewContext;
GLXContext APIENTRY glad_debug_impl_glXCreateNewContext(Display * arg0, GLXFBConfig arg1, int arg2, GLXContext arg3, Bool arg4) {    
    GLXContext ret;
    _pre_call_callback("glXCreateNewContext", (void*)glXCreateNewContext, 5, arg0, arg1, arg2, arg3, arg4);
    ret =  glad_glXCreateNewContext(arg0, arg1, arg2, arg3, arg4);
    _post_call_callback("glXCreateNewContext", (void*)glXCreateNewContext, 5, arg0, arg1, arg2, arg3, arg4);
    return ret;
}
PFNGLXCREATENEWCONTEXTPROC glad_debug_glXCreateNewContext = glad_debug_impl_glXCreateNewContext;
PFNGLXCREATEPBUFFERPROC glad_glXCreatePbuffer;
GLXPbuffer APIENTRY glad_debug_impl_glXCreatePbuffer(Display * arg0, GLXFBConfig arg1, const int * arg2) {    
    GLXPbuffer ret;
    _pre_call_callback("glXCreatePbuffer", (void*)glXCreatePbuffer, 3, arg0, arg1, arg2);
    ret =  glad_glXCreatePbuffer(arg0, arg1, arg2);
    _post_call_callback("glXCreatePbuffer", (void*)glXCreatePbuffer, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXCREATEPBUFFERPROC glad_debug_glXCreatePbuffer = glad_debug_impl_glXCreatePbuffer;
PFNGLXCREATEPIXMAPPROC glad_glXCreatePixmap;
GLXPixmap APIENTRY glad_debug_impl_glXCreatePixmap(Display * arg0, GLXFBConfig arg1, Pixmap arg2, const int * arg3) {    
    GLXPixmap ret;
    _pre_call_callback("glXCreatePixmap", (void*)glXCreatePixmap, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXCreatePixmap(arg0, arg1, arg2, arg3);
    _post_call_callback("glXCreatePixmap", (void*)glXCreatePixmap, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXCREATEPIXMAPPROC glad_debug_glXCreatePixmap = glad_debug_impl_glXCreatePixmap;
PFNGLXCREATEWINDOWPROC glad_glXCreateWindow;
GLXWindow APIENTRY glad_debug_impl_glXCreateWindow(Display * arg0, GLXFBConfig arg1, Window arg2, const int * arg3) {    
    GLXWindow ret;
    _pre_call_callback("glXCreateWindow", (void*)glXCreateWindow, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXCreateWindow(arg0, arg1, arg2, arg3);
    _post_call_callback("glXCreateWindow", (void*)glXCreateWindow, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXCREATEWINDOWPROC glad_debug_glXCreateWindow = glad_debug_impl_glXCreateWindow;
PFNGLXDESTROYCONTEXTPROC glad_glXDestroyContext;
void APIENTRY glad_debug_impl_glXDestroyContext(Display * arg0, GLXContext arg1) {    
    _pre_call_callback("glXDestroyContext", (void*)glXDestroyContext, 2, arg0, arg1);
     glad_glXDestroyContext(arg0, arg1);
    _post_call_callback("glXDestroyContext", (void*)glXDestroyContext, 2, arg0, arg1);
    
}
PFNGLXDESTROYCONTEXTPROC glad_debug_glXDestroyContext = glad_debug_impl_glXDestroyContext;
PFNGLXDESTROYGLXPIXMAPPROC glad_glXDestroyGLXPixmap;
void APIENTRY glad_debug_impl_glXDestroyGLXPixmap(Display * arg0, GLXPixmap arg1) {    
    _pre_call_callback("glXDestroyGLXPixmap", (void*)glXDestroyGLXPixmap, 2, arg0, arg1);
     glad_glXDestroyGLXPixmap(arg0, arg1);
    _post_call_callback("glXDestroyGLXPixmap", (void*)glXDestroyGLXPixmap, 2, arg0, arg1);
    
}
PFNGLXDESTROYGLXPIXMAPPROC glad_debug_glXDestroyGLXPixmap = glad_debug_impl_glXDestroyGLXPixmap;
PFNGLXDESTROYPBUFFERPROC glad_glXDestroyPbuffer;
void APIENTRY glad_debug_impl_glXDestroyPbuffer(Display * arg0, GLXPbuffer arg1) {    
    _pre_call_callback("glXDestroyPbuffer", (void*)glXDestroyPbuffer, 2, arg0, arg1);
     glad_glXDestroyPbuffer(arg0, arg1);
    _post_call_callback("glXDestroyPbuffer", (void*)glXDestroyPbuffer, 2, arg0, arg1);
    
}
PFNGLXDESTROYPBUFFERPROC glad_debug_glXDestroyPbuffer = glad_debug_impl_glXDestroyPbuffer;
PFNGLXDESTROYPIXMAPPROC glad_glXDestroyPixmap;
void APIENTRY glad_debug_impl_glXDestroyPixmap(Display * arg0, GLXPixmap arg1) {    
    _pre_call_callback("glXDestroyPixmap", (void*)glXDestroyPixmap, 2, arg0, arg1);
     glad_glXDestroyPixmap(arg0, arg1);
    _post_call_callback("glXDestroyPixmap", (void*)glXDestroyPixmap, 2, arg0, arg1);
    
}
PFNGLXDESTROYPIXMAPPROC glad_debug_glXDestroyPixmap = glad_debug_impl_glXDestroyPixmap;
PFNGLXDESTROYWINDOWPROC glad_glXDestroyWindow;
void APIENTRY glad_debug_impl_glXDestroyWindow(Display * arg0, GLXWindow arg1) {    
    _pre_call_callback("glXDestroyWindow", (void*)glXDestroyWindow, 2, arg0, arg1);
     glad_glXDestroyWindow(arg0, arg1);
    _post_call_callback("glXDestroyWindow", (void*)glXDestroyWindow, 2, arg0, arg1);
    
}
PFNGLXDESTROYWINDOWPROC glad_debug_glXDestroyWindow = glad_debug_impl_glXDestroyWindow;
PFNGLXGETCLIENTSTRINGPROC glad_glXGetClientString;
const char * APIENTRY glad_debug_impl_glXGetClientString(Display * arg0, int arg1) {    
    const char * ret;
    _pre_call_callback("glXGetClientString", (void*)glXGetClientString, 2, arg0, arg1);
    ret =  glad_glXGetClientString(arg0, arg1);
    _post_call_callback("glXGetClientString", (void*)glXGetClientString, 2, arg0, arg1);
    return ret;
}
PFNGLXGETCLIENTSTRINGPROC glad_debug_glXGetClientString = glad_debug_impl_glXGetClientString;
PFNGLXGETCONFIGPROC glad_glXGetConfig;
int APIENTRY glad_debug_impl_glXGetConfig(Display * arg0, XVisualInfo * arg1, int arg2, int * arg3) {    
    int ret;
    _pre_call_callback("glXGetConfig", (void*)glXGetConfig, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXGetConfig(arg0, arg1, arg2, arg3);
    _post_call_callback("glXGetConfig", (void*)glXGetConfig, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXGETCONFIGPROC glad_debug_glXGetConfig = glad_debug_impl_glXGetConfig;
PFNGLXGETCURRENTCONTEXTPROC glad_glXGetCurrentContext;
GLXContext APIENTRY glad_debug_impl_glXGetCurrentContext(void) {    
    GLXContext ret;
    _pre_call_callback("glXGetCurrentContext", (void*)glXGetCurrentContext, 0);
    ret =  glad_glXGetCurrentContext();
    _post_call_callback("glXGetCurrentContext", (void*)glXGetCurrentContext, 0);
    return ret;
}
PFNGLXGETCURRENTCONTEXTPROC glad_debug_glXGetCurrentContext = glad_debug_impl_glXGetCurrentContext;
PFNGLXGETCURRENTDISPLAYPROC glad_glXGetCurrentDisplay;
Display * APIENTRY glad_debug_impl_glXGetCurrentDisplay(void) {    
    Display * ret;
    _pre_call_callback("glXGetCurrentDisplay", (void*)glXGetCurrentDisplay, 0);
    ret =  glad_glXGetCurrentDisplay();
    _post_call_callback("glXGetCurrentDisplay", (void*)glXGetCurrentDisplay, 0);
    return ret;
}
PFNGLXGETCURRENTDISPLAYPROC glad_debug_glXGetCurrentDisplay = glad_debug_impl_glXGetCurrentDisplay;
PFNGLXGETCURRENTDRAWABLEPROC glad_glXGetCurrentDrawable;
GLXDrawable APIENTRY glad_debug_impl_glXGetCurrentDrawable(void) {    
    GLXDrawable ret;
    _pre_call_callback("glXGetCurrentDrawable", (void*)glXGetCurrentDrawable, 0);
    ret =  glad_glXGetCurrentDrawable();
    _post_call_callback("glXGetCurrentDrawable", (void*)glXGetCurrentDrawable, 0);
    return ret;
}
PFNGLXGETCURRENTDRAWABLEPROC glad_debug_glXGetCurrentDrawable = glad_debug_impl_glXGetCurrentDrawable;
PFNGLXGETCURRENTREADDRAWABLEPROC glad_glXGetCurrentReadDrawable;
GLXDrawable APIENTRY glad_debug_impl_glXGetCurrentReadDrawable(void) {    
    GLXDrawable ret;
    _pre_call_callback("glXGetCurrentReadDrawable", (void*)glXGetCurrentReadDrawable, 0);
    ret =  glad_glXGetCurrentReadDrawable();
    _post_call_callback("glXGetCurrentReadDrawable", (void*)glXGetCurrentReadDrawable, 0);
    return ret;
}
PFNGLXGETCURRENTREADDRAWABLEPROC glad_debug_glXGetCurrentReadDrawable = glad_debug_impl_glXGetCurrentReadDrawable;
PFNGLXGETFBCONFIGATTRIBPROC glad_glXGetFBConfigAttrib;
int APIENTRY glad_debug_impl_glXGetFBConfigAttrib(Display * arg0, GLXFBConfig arg1, int arg2, int * arg3) {    
    int ret;
    _pre_call_callback("glXGetFBConfigAttrib", (void*)glXGetFBConfigAttrib, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXGetFBConfigAttrib(arg0, arg1, arg2, arg3);
    _post_call_callback("glXGetFBConfigAttrib", (void*)glXGetFBConfigAttrib, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXGETFBCONFIGATTRIBPROC glad_debug_glXGetFBConfigAttrib = glad_debug_impl_glXGetFBConfigAttrib;
PFNGLXGETFBCONFIGSPROC glad_glXGetFBConfigs;
GLXFBConfig * APIENTRY glad_debug_impl_glXGetFBConfigs(Display * arg0, int arg1, int * arg2) {    
    GLXFBConfig * ret;
    _pre_call_callback("glXGetFBConfigs", (void*)glXGetFBConfigs, 3, arg0, arg1, arg2);
    ret =  glad_glXGetFBConfigs(arg0, arg1, arg2);
    _post_call_callback("glXGetFBConfigs", (void*)glXGetFBConfigs, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXGETFBCONFIGSPROC glad_debug_glXGetFBConfigs = glad_debug_impl_glXGetFBConfigs;
PFNGLXGETPROCADDRESSPROC glad_glXGetProcAddress;
__GLXextFuncPtr APIENTRY glad_debug_impl_glXGetProcAddress(const GLubyte * arg0) {    
    __GLXextFuncPtr ret;
    _pre_call_callback("glXGetProcAddress", (void*)glXGetProcAddress, 1, arg0);
    ret =  glad_glXGetProcAddress(arg0);
    _post_call_callback("glXGetProcAddress", (void*)glXGetProcAddress, 1, arg0);
    return ret;
}
PFNGLXGETPROCADDRESSPROC glad_debug_glXGetProcAddress = glad_debug_impl_glXGetProcAddress;
PFNGLXGETSELECTEDEVENTPROC glad_glXGetSelectedEvent;
void APIENTRY glad_debug_impl_glXGetSelectedEvent(Display * arg0, GLXDrawable arg1, unsigned long * arg2) {    
    _pre_call_callback("glXGetSelectedEvent", (void*)glXGetSelectedEvent, 3, arg0, arg1, arg2);
     glad_glXGetSelectedEvent(arg0, arg1, arg2);
    _post_call_callback("glXGetSelectedEvent", (void*)glXGetSelectedEvent, 3, arg0, arg1, arg2);
    
}
PFNGLXGETSELECTEDEVENTPROC glad_debug_glXGetSelectedEvent = glad_debug_impl_glXGetSelectedEvent;
PFNGLXGETVISUALFROMFBCONFIGPROC glad_glXGetVisualFromFBConfig;
XVisualInfo * APIENTRY glad_debug_impl_glXGetVisualFromFBConfig(Display * arg0, GLXFBConfig arg1) {    
    XVisualInfo * ret;
    _pre_call_callback("glXGetVisualFromFBConfig", (void*)glXGetVisualFromFBConfig, 2, arg0, arg1);
    ret =  glad_glXGetVisualFromFBConfig(arg0, arg1);
    _post_call_callback("glXGetVisualFromFBConfig", (void*)glXGetVisualFromFBConfig, 2, arg0, arg1);
    return ret;
}
PFNGLXGETVISUALFROMFBCONFIGPROC glad_debug_glXGetVisualFromFBConfig = glad_debug_impl_glXGetVisualFromFBConfig;
PFNGLXISDIRECTPROC glad_glXIsDirect;
Bool APIENTRY glad_debug_impl_glXIsDirect(Display * arg0, GLXContext arg1) {    
    Bool ret;
    _pre_call_callback("glXIsDirect", (void*)glXIsDirect, 2, arg0, arg1);
    ret =  glad_glXIsDirect(arg0, arg1);
    _post_call_callback("glXIsDirect", (void*)glXIsDirect, 2, arg0, arg1);
    return ret;
}
PFNGLXISDIRECTPROC glad_debug_glXIsDirect = glad_debug_impl_glXIsDirect;
PFNGLXMAKECONTEXTCURRENTPROC glad_glXMakeContextCurrent;
Bool APIENTRY glad_debug_impl_glXMakeContextCurrent(Display * arg0, GLXDrawable arg1, GLXDrawable arg2, GLXContext arg3) {    
    Bool ret;
    _pre_call_callback("glXMakeContextCurrent", (void*)glXMakeContextCurrent, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXMakeContextCurrent(arg0, arg1, arg2, arg3);
    _post_call_callback("glXMakeContextCurrent", (void*)glXMakeContextCurrent, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXMAKECONTEXTCURRENTPROC glad_debug_glXMakeContextCurrent = glad_debug_impl_glXMakeContextCurrent;
PFNGLXMAKECURRENTPROC glad_glXMakeCurrent;
Bool APIENTRY glad_debug_impl_glXMakeCurrent(Display * arg0, GLXDrawable arg1, GLXContext arg2) {    
    Bool ret;
    _pre_call_callback("glXMakeCurrent", (void*)glXMakeCurrent, 3, arg0, arg1, arg2);
    ret =  glad_glXMakeCurrent(arg0, arg1, arg2);
    _post_call_callback("glXMakeCurrent", (void*)glXMakeCurrent, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXMAKECURRENTPROC glad_debug_glXMakeCurrent = glad_debug_impl_glXMakeCurrent;
PFNGLXQUERYCONTEXTPROC glad_glXQueryContext;
int APIENTRY glad_debug_impl_glXQueryContext(Display * arg0, GLXContext arg1, int arg2, int * arg3) {    
    int ret;
    _pre_call_callback("glXQueryContext", (void*)glXQueryContext, 4, arg0, arg1, arg2, arg3);
    ret =  glad_glXQueryContext(arg0, arg1, arg2, arg3);
    _post_call_callback("glXQueryContext", (void*)glXQueryContext, 4, arg0, arg1, arg2, arg3);
    return ret;
}
PFNGLXQUERYCONTEXTPROC glad_debug_glXQueryContext = glad_debug_impl_glXQueryContext;
PFNGLXQUERYDRAWABLEPROC glad_glXQueryDrawable;
void APIENTRY glad_debug_impl_glXQueryDrawable(Display * arg0, GLXDrawable arg1, int arg2, unsigned int * arg3) {    
    _pre_call_callback("glXQueryDrawable", (void*)glXQueryDrawable, 4, arg0, arg1, arg2, arg3);
     glad_glXQueryDrawable(arg0, arg1, arg2, arg3);
    _post_call_callback("glXQueryDrawable", (void*)glXQueryDrawable, 4, arg0, arg1, arg2, arg3);
    
}
PFNGLXQUERYDRAWABLEPROC glad_debug_glXQueryDrawable = glad_debug_impl_glXQueryDrawable;
PFNGLXQUERYEXTENSIONPROC glad_glXQueryExtension;
Bool APIENTRY glad_debug_impl_glXQueryExtension(Display * arg0, int * arg1, int * arg2) {    
    Bool ret;
    _pre_call_callback("glXQueryExtension", (void*)glXQueryExtension, 3, arg0, arg1, arg2);
    ret =  glad_glXQueryExtension(arg0, arg1, arg2);
    _post_call_callback("glXQueryExtension", (void*)glXQueryExtension, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXQUERYEXTENSIONPROC glad_debug_glXQueryExtension = glad_debug_impl_glXQueryExtension;
PFNGLXQUERYEXTENSIONSSTRINGPROC glad_glXQueryExtensionsString;
const char * APIENTRY glad_debug_impl_glXQueryExtensionsString(Display * arg0, int arg1) {    
    const char * ret;
    _pre_call_callback("glXQueryExtensionsString", (void*)glXQueryExtensionsString, 2, arg0, arg1);
    ret =  glad_glXQueryExtensionsString(arg0, arg1);
    _post_call_callback("glXQueryExtensionsString", (void*)glXQueryExtensionsString, 2, arg0, arg1);
    return ret;
}
PFNGLXQUERYEXTENSIONSSTRINGPROC glad_debug_glXQueryExtensionsString = glad_debug_impl_glXQueryExtensionsString;
PFNGLXQUERYSERVERSTRINGPROC glad_glXQueryServerString;
const char * APIENTRY glad_debug_impl_glXQueryServerString(Display * arg0, int arg1, int arg2) {    
    const char * ret;
    _pre_call_callback("glXQueryServerString", (void*)glXQueryServerString, 3, arg0, arg1, arg2);
    ret =  glad_glXQueryServerString(arg0, arg1, arg2);
    _post_call_callback("glXQueryServerString", (void*)glXQueryServerString, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXQUERYSERVERSTRINGPROC glad_debug_glXQueryServerString = glad_debug_impl_glXQueryServerString;
PFNGLXQUERYVERSIONPROC glad_glXQueryVersion;
Bool APIENTRY glad_debug_impl_glXQueryVersion(Display * arg0, int * arg1, int * arg2) {    
    Bool ret;
    _pre_call_callback("glXQueryVersion", (void*)glXQueryVersion, 3, arg0, arg1, arg2);
    ret =  glad_glXQueryVersion(arg0, arg1, arg2);
    _post_call_callback("glXQueryVersion", (void*)glXQueryVersion, 3, arg0, arg1, arg2);
    return ret;
}
PFNGLXQUERYVERSIONPROC glad_debug_glXQueryVersion = glad_debug_impl_glXQueryVersion;
PFNGLXSELECTEVENTPROC glad_glXSelectEvent;
void APIENTRY glad_debug_impl_glXSelectEvent(Display * arg0, GLXDrawable arg1, unsigned long arg2) {    
    _pre_call_callback("glXSelectEvent", (void*)glXSelectEvent, 3, arg0, arg1, arg2);
     glad_glXSelectEvent(arg0, arg1, arg2);
    _post_call_callback("glXSelectEvent", (void*)glXSelectEvent, 3, arg0, arg1, arg2);
    
}
PFNGLXSELECTEVENTPROC glad_debug_glXSelectEvent = glad_debug_impl_glXSelectEvent;
PFNGLXSWAPBUFFERSPROC glad_glXSwapBuffers;
void APIENTRY glad_debug_impl_glXSwapBuffers(Display * arg0, GLXDrawable arg1) {    
    _pre_call_callback("glXSwapBuffers", (void*)glXSwapBuffers, 2, arg0, arg1);
     glad_glXSwapBuffers(arg0, arg1);
    _post_call_callback("glXSwapBuffers", (void*)glXSwapBuffers, 2, arg0, arg1);
    
}
PFNGLXSWAPBUFFERSPROC glad_debug_glXSwapBuffers = glad_debug_impl_glXSwapBuffers;
PFNGLXUSEXFONTPROC glad_glXUseXFont;
void APIENTRY glad_debug_impl_glXUseXFont(Font arg0, int arg1, int arg2, int arg3) {    
    _pre_call_callback("glXUseXFont", (void*)glXUseXFont, 4, arg0, arg1, arg2, arg3);
     glad_glXUseXFont(arg0, arg1, arg2, arg3);
    _post_call_callback("glXUseXFont", (void*)glXUseXFont, 4, arg0, arg1, arg2, arg3);
    
}
PFNGLXUSEXFONTPROC glad_debug_glXUseXFont = glad_debug_impl_glXUseXFont;
PFNGLXWAITGLPROC glad_glXWaitGL;
void APIENTRY glad_debug_impl_glXWaitGL(void) {    
    _pre_call_callback("glXWaitGL", (void*)glXWaitGL, 0);
     glad_glXWaitGL();
    _post_call_callback("glXWaitGL", (void*)glXWaitGL, 0);
    
}
PFNGLXWAITGLPROC glad_debug_glXWaitGL = glad_debug_impl_glXWaitGL;
PFNGLXWAITXPROC glad_glXWaitX;
void APIENTRY glad_debug_impl_glXWaitX(void) {    
    _pre_call_callback("glXWaitX", (void*)glXWaitX, 0);
     glad_glXWaitX();
    _post_call_callback("glXWaitX", (void*)glXWaitX, 0);
    
}
PFNGLXWAITXPROC glad_debug_glXWaitX = glad_debug_impl_glXWaitX;
int GLAD_GLX_ARB_create_context = 0;
int GLAD_GLX_ARB_create_context_profile = 0;
int GLAD_GLX_EXT_swap_control = 0;
int GLAD_GLX_SGIX_pbuffer = 0;
PFNGLXCREATECONTEXTATTRIBSARBPROC glad_glXCreateContextAttribsARB;
GLXContext APIENTRY glad_debug_impl_glXCreateContextAttribsARB(Display * arg0, GLXFBConfig arg1, GLXContext arg2, Bool arg3, const int * arg4) {    
    GLXContext ret;
    _pre_call_callback("glXCreateContextAttribsARB", (void*)glXCreateContextAttribsARB, 5, arg0, arg1, arg2, arg3, arg4);
    ret =  glad_glXCreateContextAttribsARB(arg0, arg1, arg2, arg3, arg4);
    _post_call_callback("glXCreateContextAttribsARB", (void*)glXCreateContextAttribsARB, 5, arg0, arg1, arg2, arg3, arg4);
    return ret;
}
PFNGLXCREATECONTEXTATTRIBSARBPROC glad_debug_glXCreateContextAttribsARB = glad_debug_impl_glXCreateContextAttribsARB;
PFNGLXSWAPINTERVALEXTPROC glad_glXSwapIntervalEXT;
void APIENTRY glad_debug_impl_glXSwapIntervalEXT(Display * arg0, GLXDrawable arg1, int arg2) {    
    _pre_call_callback("glXSwapIntervalEXT", (void*)glXSwapIntervalEXT, 3, arg0, arg1, arg2);
     glad_glXSwapIntervalEXT(arg0, arg1, arg2);
    _post_call_callback("glXSwapIntervalEXT", (void*)glXSwapIntervalEXT, 3, arg0, arg1, arg2);
    
}
PFNGLXSWAPINTERVALEXTPROC glad_debug_glXSwapIntervalEXT = glad_debug_impl_glXSwapIntervalEXT;
PFNGLXCREATEGLXPBUFFERSGIXPROC glad_glXCreateGLXPbufferSGIX;
GLXPbufferSGIX APIENTRY glad_debug_impl_glXCreateGLXPbufferSGIX(Display * arg0, GLXFBConfigSGIX arg1, unsigned int arg2, unsigned int arg3, int * arg4) {    
    GLXPbufferSGIX ret;
    _pre_call_callback("glXCreateGLXPbufferSGIX", (void*)glXCreateGLXPbufferSGIX, 5, arg0, arg1, arg2, arg3, arg4);
    ret =  glad_glXCreateGLXPbufferSGIX(arg0, arg1, arg2, arg3, arg4);
    _post_call_callback("glXCreateGLXPbufferSGIX", (void*)glXCreateGLXPbufferSGIX, 5, arg0, arg1, arg2, arg3, arg4);
    return ret;
}
PFNGLXCREATEGLXPBUFFERSGIXPROC glad_debug_glXCreateGLXPbufferSGIX = glad_debug_impl_glXCreateGLXPbufferSGIX;
PFNGLXDESTROYGLXPBUFFERSGIXPROC glad_glXDestroyGLXPbufferSGIX;
void APIENTRY glad_debug_impl_glXDestroyGLXPbufferSGIX(Display * arg0, GLXPbufferSGIX arg1) {    
    _pre_call_callback("glXDestroyGLXPbufferSGIX", (void*)glXDestroyGLXPbufferSGIX, 2, arg0, arg1);
     glad_glXDestroyGLXPbufferSGIX(arg0, arg1);
    _post_call_callback("glXDestroyGLXPbufferSGIX", (void*)glXDestroyGLXPbufferSGIX, 2, arg0, arg1);
    
}
PFNGLXDESTROYGLXPBUFFERSGIXPROC glad_debug_glXDestroyGLXPbufferSGIX = glad_debug_impl_glXDestroyGLXPbufferSGIX;
PFNGLXQUERYGLXPBUFFERSGIXPROC glad_glXQueryGLXPbufferSGIX;
void APIENTRY glad_debug_impl_glXQueryGLXPbufferSGIX(Display * arg0, GLXPbufferSGIX arg1, int arg2, unsigned int * arg3) {    
    _pre_call_callback("glXQueryGLXPbufferSGIX", (void*)glXQueryGLXPbufferSGIX, 4, arg0, arg1, arg2, arg3);
     glad_glXQueryGLXPbufferSGIX(arg0, arg1, arg2, arg3);
    _post_call_callback("glXQueryGLXPbufferSGIX", (void*)glXQueryGLXPbufferSGIX, 4, arg0, arg1, arg2, arg3);
    
}
PFNGLXQUERYGLXPBUFFERSGIXPROC glad_debug_glXQueryGLXPbufferSGIX = glad_debug_impl_glXQueryGLXPbufferSGIX;
PFNGLXSELECTEVENTSGIXPROC glad_glXSelectEventSGIX;
void APIENTRY glad_debug_impl_glXSelectEventSGIX(Display * arg0, GLXDrawable arg1, unsigned long arg2) {    
    _pre_call_callback("glXSelectEventSGIX", (void*)glXSelectEventSGIX, 3, arg0, arg1, arg2);
     glad_glXSelectEventSGIX(arg0, arg1, arg2);
    _post_call_callback("glXSelectEventSGIX", (void*)glXSelectEventSGIX, 3, arg0, arg1, arg2);
    
}
PFNGLXSELECTEVENTSGIXPROC glad_debug_glXSelectEventSGIX = glad_debug_impl_glXSelectEventSGIX;
PFNGLXGETSELECTEDEVENTSGIXPROC glad_glXGetSelectedEventSGIX;
void APIENTRY glad_debug_impl_glXGetSelectedEventSGIX(Display * arg0, GLXDrawable arg1, unsigned long * arg2) {    
    _pre_call_callback("glXGetSelectedEventSGIX", (void*)glXGetSelectedEventSGIX, 3, arg0, arg1, arg2);
     glad_glXGetSelectedEventSGIX(arg0, arg1, arg2);
    _post_call_callback("glXGetSelectedEventSGIX", (void*)glXGetSelectedEventSGIX, 3, arg0, arg1, arg2);
    
}
PFNGLXGETSELECTEDEVENTSGIXPROC glad_debug_glXGetSelectedEventSGIX = glad_debug_impl_glXGetSelectedEventSGIX;
static void load_GLX_VERSION_1_0(GLADloadproc load) {
	if(!GLAD_GLX_VERSION_1_0) return;
	glad_glXChooseVisual = (PFNGLXCHOOSEVISUALPROC)load("glXChooseVisual");
	glad_glXCreateContext = (PFNGLXCREATECONTEXTPROC)load("glXCreateContext");
	glad_glXDestroyContext = (PFNGLXDESTROYCONTEXTPROC)load("glXDestroyContext");
	glad_glXMakeCurrent = (PFNGLXMAKECURRENTPROC)load("glXMakeCurrent");
	glad_glXCopyContext = (PFNGLXCOPYCONTEXTPROC)load("glXCopyContext");
	glad_glXSwapBuffers = (PFNGLXSWAPBUFFERSPROC)load("glXSwapBuffers");
	glad_glXCreateGLXPixmap = (PFNGLXCREATEGLXPIXMAPPROC)load("glXCreateGLXPixmap");
	glad_glXDestroyGLXPixmap = (PFNGLXDESTROYGLXPIXMAPPROC)load("glXDestroyGLXPixmap");
	glad_glXQueryExtension = (PFNGLXQUERYEXTENSIONPROC)load("glXQueryExtension");
	glad_glXQueryVersion = (PFNGLXQUERYVERSIONPROC)load("glXQueryVersion");
	glad_glXIsDirect = (PFNGLXISDIRECTPROC)load("glXIsDirect");
	glad_glXGetConfig = (PFNGLXGETCONFIGPROC)load("glXGetConfig");
	glad_glXGetCurrentContext = (PFNGLXGETCURRENTCONTEXTPROC)load("glXGetCurrentContext");
	glad_glXGetCurrentDrawable = (PFNGLXGETCURRENTDRAWABLEPROC)load("glXGetCurrentDrawable");
	glad_glXWaitGL = (PFNGLXWAITGLPROC)load("glXWaitGL");
	glad_glXWaitX = (PFNGLXWAITXPROC)load("glXWaitX");
	glad_glXUseXFont = (PFNGLXUSEXFONTPROC)load("glXUseXFont");
}
static void load_GLX_VERSION_1_1(GLADloadproc load) {
	if(!GLAD_GLX_VERSION_1_1) return;
	glad_glXQueryExtensionsString = (PFNGLXQUERYEXTENSIONSSTRINGPROC)load("glXQueryExtensionsString");
	glad_glXQueryServerString = (PFNGLXQUERYSERVERSTRINGPROC)load("glXQueryServerString");
	glad_glXGetClientString = (PFNGLXGETCLIENTSTRINGPROC)load("glXGetClientString");
}
static void load_GLX_VERSION_1_2(GLADloadproc load) {
	if(!GLAD_GLX_VERSION_1_2) return;
	glad_glXGetCurrentDisplay = (PFNGLXGETCURRENTDISPLAYPROC)load("glXGetCurrentDisplay");
}
static void load_GLX_VERSION_1_3(GLADloadproc load) {
	if(!GLAD_GLX_VERSION_1_3) return;
	glad_glXGetFBConfigs = (PFNGLXGETFBCONFIGSPROC)load("glXGetFBConfigs");
	glad_glXChooseFBConfig = (PFNGLXCHOOSEFBCONFIGPROC)load("glXChooseFBConfig");
	glad_glXGetFBConfigAttrib = (PFNGLXGETFBCONFIGATTRIBPROC)load("glXGetFBConfigAttrib");
	glad_glXGetVisualFromFBConfig = (PFNGLXGETVISUALFROMFBCONFIGPROC)load("glXGetVisualFromFBConfig");
	glad_glXCreateWindow = (PFNGLXCREATEWINDOWPROC)load("glXCreateWindow");
	glad_glXDestroyWindow = (PFNGLXDESTROYWINDOWPROC)load("glXDestroyWindow");
	glad_glXCreatePixmap = (PFNGLXCREATEPIXMAPPROC)load("glXCreatePixmap");
	glad_glXDestroyPixmap = (PFNGLXDESTROYPIXMAPPROC)load("glXDestroyPixmap");
	glad_glXCreatePbuffer = (PFNGLXCREATEPBUFFERPROC)load("glXCreatePbuffer");
	glad_glXDestroyPbuffer = (PFNGLXDESTROYPBUFFERPROC)load("glXDestroyPbuffer");
	glad_glXQueryDrawable = (PFNGLXQUERYDRAWABLEPROC)load("glXQueryDrawable");
	glad_glXCreateNewContext = (PFNGLXCREATENEWCONTEXTPROC)load("glXCreateNewContext");
	glad_glXMakeContextCurrent = (PFNGLXMAKECONTEXTCURRENTPROC)load("glXMakeContextCurrent");
	glad_glXGetCurrentReadDrawable = (PFNGLXGETCURRENTREADDRAWABLEPROC)load("glXGetCurrentReadDrawable");
	glad_glXQueryContext = (PFNGLXQUERYCONTEXTPROC)load("glXQueryContext");
	glad_glXSelectEvent = (PFNGLXSELECTEVENTPROC)load("glXSelectEvent");
	glad_glXGetSelectedEvent = (PFNGLXGETSELECTEDEVENTPROC)load("glXGetSelectedEvent");
}
static void load_GLX_VERSION_1_4(GLADloadproc load) {
	if(!GLAD_GLX_VERSION_1_4) return;
	glad_glXGetProcAddress = (PFNGLXGETPROCADDRESSPROC)load("glXGetProcAddress");
}
static void load_GLX_ARB_create_context(GLADloadproc load) {
	if(!GLAD_GLX_ARB_create_context) return;
	glad_glXCreateContextAttribsARB = (PFNGLXCREATECONTEXTATTRIBSARBPROC)load("glXCreateContextAttribsARB");
}
static void load_GLX_EXT_swap_control(GLADloadproc load) {
	if(!GLAD_GLX_EXT_swap_control) return;
	glad_glXSwapIntervalEXT = (PFNGLXSWAPINTERVALEXTPROC)load("glXSwapIntervalEXT");
}
static void load_GLX_SGIX_pbuffer(GLADloadproc load) {
	if(!GLAD_GLX_SGIX_pbuffer) return;
	glad_glXCreateGLXPbufferSGIX = (PFNGLXCREATEGLXPBUFFERSGIXPROC)load("glXCreateGLXPbufferSGIX");
	glad_glXDestroyGLXPbufferSGIX = (PFNGLXDESTROYGLXPBUFFERSGIXPROC)load("glXDestroyGLXPbufferSGIX");
	glad_glXQueryGLXPbufferSGIX = (PFNGLXQUERYGLXPBUFFERSGIXPROC)load("glXQueryGLXPbufferSGIX");
	glad_glXSelectEventSGIX = (PFNGLXSELECTEVENTSGIXPROC)load("glXSelectEventSGIX");
	glad_glXGetSelectedEventSGIX = (PFNGLXGETSELECTEDEVENTSGIXPROC)load("glXGetSelectedEventSGIX");
}
static int find_extensionsGLX(void) {
	if (!get_exts()) return 0;
	GLAD_GLX_ARB_create_context = has_ext("GLX_ARB_create_context");
	GLAD_GLX_ARB_create_context_profile = has_ext("GLX_ARB_create_context_profile");
	GLAD_GLX_EXT_swap_control = has_ext("GLX_EXT_swap_control");
	GLAD_GLX_SGIX_pbuffer = has_ext("GLX_SGIX_pbuffer");
	free_exts();
	return 1;
}

static void find_coreGLX(Display *dpy, int screen) {
	int major = 0, minor = 0;
	if(dpy == 0 && GLADGLXDisplay == 0) {
		dpy = XOpenDisplay(0);
		screen = XScreenNumberOfScreen(XDefaultScreenOfDisplay(dpy));
	} else if(dpy == 0) {
		dpy = GLADGLXDisplay;
		screen = GLADGLXscreen;
	}
	glXQueryVersion(dpy, &major, &minor);
	GLADGLXDisplay = dpy;
	GLADGLXscreen = screen;
	GLAD_GLX_VERSION_1_0 = (major == 1 && minor >= 0) || major > 1;
	GLAD_GLX_VERSION_1_1 = (major == 1 && minor >= 1) || major > 1;
	GLAD_GLX_VERSION_1_2 = (major == 1 && minor >= 2) || major > 1;
	GLAD_GLX_VERSION_1_3 = (major == 1 && minor >= 3) || major > 1;
	GLAD_GLX_VERSION_1_4 = (major == 1 && minor >= 4) || major > 1;
}

int gladLoadGLXLoader(GLADloadproc load, Display *dpy, int screen) {
	glXQueryVersion = (PFNGLXQUERYVERSIONPROC)load("glXQueryVersion");
	if(glXQueryVersion == NULL) return 0;
	find_coreGLX(dpy, screen);
	load_GLX_VERSION_1_0(load);
	load_GLX_VERSION_1_1(load);
	load_GLX_VERSION_1_2(load);
	load_GLX_VERSION_1_3(load);
	load_GLX_VERSION_1_4(load);

	if (!find_extensionsGLX()) return 0;
	load_GLX_ARB_create_context(load);
	load_GLX_EXT_swap_control(load);
	load_GLX_SGIX_pbuffer(load);
	return 1;
}

