#pragma once
#include <common/bitfield.h>
#include <cstdint>

namespace latte
{

BITFIELD_BEG(TD_PS_SAMPLER_BORDERN_RED, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_RED)
BITFIELD_END

BITFIELD_BEG(TD_PS_SAMPLER_BORDERN_GREEN, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_GREEN)
BITFIELD_END

BITFIELD_BEG(TD_PS_SAMPLER_BORDERN_BLUE, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_BLUE)
BITFIELD_END

BITFIELD_BEG(TD_PS_SAMPLER_BORDERN_ALPHA, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_ALPHA)
BITFIELD_END

BITFIELD_BEG(TD_VS_SAMPLER_BORDERN_RED, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_RED)
BITFIELD_END

BITFIELD_BEG(TD_VS_SAMPLER_BORDERN_GREEN, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_GREEN)
BITFIELD_END

BITFIELD_BEG(TD_VS_SAMPLER_BORDERN_BLUE, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_BLUE)
BITFIELD_END

BITFIELD_BEG(TD_VS_SAMPLER_BORDERN_ALPHA, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_ALPHA)
BITFIELD_END

BITFIELD_BEG(TD_GS_SAMPLER_BORDERN_RED, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_RED)
BITFIELD_END

BITFIELD_BEG(TD_GS_SAMPLER_BORDERN_GREEN, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_GREEN)
BITFIELD_END

BITFIELD_BEG(TD_GS_SAMPLER_BORDERN_BLUE, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_BLUE)
BITFIELD_END

BITFIELD_BEG(TD_GS_SAMPLER_BORDERN_ALPHA, uint32_t)
   BITFIELD_ENTRY(0, 32, float, BORDER_ALPHA)
BITFIELD_END

} // namespace latte
